### ISSUE TITLE
Fixed Cors Issue 

### ISSUE THREAD

**Issue by mharoot** [vanessailana/Comp-680#1]
Fixed Form to validate when message sent is successful vs fails

Frontend : POST was "name" "email" "content" in the SupportForm Service 
Backend : SupportController expecting: "email" , "message"

application.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=username
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

Marvin H

**Comment by vanessailana** [comment]
This issue can be closed
